#pragma once

#include <project_version.h>

#define VERSION_MAJOR PROJECT_VERSION_MAJOR
#define VERSION_MINOR PROJECT_VERSION_MINOR
#define VERSION_PATCH PROJECT_VERSION_PATCH
#define VERSION_BUILD PROJECT_VERSION_BUILD
#define VERSION_STABILITY PROJECT_VERSION_STABILITY

#include <sversion.h>
