#pragma once

#define VERSION_STRINGIFY(n) VERSION_STRINGIFY_HELPER(n)
#define VERSION_STRINGIFY_HELPER(n) #n

#define VERSION_STRING \
     VERSION_STRINGIFY(VERSION_MAJOR) "." \
     VERSION_STRINGIFY(VERSION_MINOR) "." \
     VERSION_STRINGIFY(VERSION_PATCH)

#define VERSION_FULL \
     VERSION_STRINGIFY(VERSION_MAJOR) "." \
     VERSION_STRINGIFY(VERSION_MINOR) "." \
     VERSION_STRINGIFY(VERSION_PATCH) \
	 VERSION_STABILITY "+" \
	 VERSION_STRINGIFY(VERSION_BUILD)

#define VERSION_STRING_SHORT \
     VERSION_STRINGIFY(PROGRAM_VERSION_MAJOR) "." \
     VERSION_STRINGIFY(PROGRAM_VERSION_MINOR)

#define VERSION_RC VERSION_MAJOR ##, ##VERSION_MINOR ##, ##VERSION_PATCH
